[package]
name = "example_plugin"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = [ "cdylib" ]

[dependencies]
egui.workspace = true
egui_wings.workspace = true
example_host.workspace = true
wings.workspace = true